version: 0.2

phases:
  install:
    commands:
      - echo "Install Phase"

  build:
    commands:
      - echo "Build Started"
      - python app.py

  post_build:
    commands:
      - echo "Build Completed"

artifacts:
  files:
    - '**/*'