version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting Docker Build"

  build:
    commands:
      - docker --version
      - docker build -t codebuild-demo .

  post_build:
    commands:
      - echo "Docker Build Completed"